pipeline {
    agent any
        stage('Build') {
            steps {
                git credentialsId: git credentialsId: '5a7c9d41-962d-44ca-8a27-49348f8b6e59', url: 'https://github.com/garcin21/maven.git'
            }
        }

    }
